blueheart:
  api:
    url: http://api-ai.vivo.com.cn
    appId: 2025539024
    appKey: FJcYydOovteRQFLj
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eduassist
    username: 26307
    password: 1234
  mybatis:
    mapper-locations: classpath:mapper/*.xml
jwt:
  secret: a1b2c3d4e5f6g7h8i9j0
  expiration: 3600